apiVersion: 1
providers:
  - name: SpaceFarm
    orgId: 1
    folder: SpaceFarm
    type: file
    disableDeletion: true
    allowUiUpdates: false
    updateIntervalSeconds: 30
    options:
      path: /var/lib/grafana/dashboards
